### ISSUE TITLE
Ändern der Mailadresse schlägt fehl

### ISSUE THREAD

**Issue by stonerl** [WaDoku/GLB#11]
Die Änderung der E-Mail-Adresse im Nutzerkonto wird nicht übernommen.

**Comment by stonerl** [comment]
Changing the email-address does work but one still gets a misleading (false) error message:

![screenshot-buddhismus-lexikon eu 2001 2015-12-17 13-03-37](https://cloud.githubusercontent.com/assets/2091312/11869277/c6e0d362-a4be-11e5-9048-6b2a702e8574.png)

**Comment by Netznarkose** [comment]
I tested this issue manually and come to the same result as stonerl, the error message is still wrong.

**Comment by stonerl** [comment]
Close as fixed.
