### ISSUE TITLE
Entries are not found although they should be in the DB

### ISSUE THREAD

**Issue by stonerl** [WaDoku/GLB#12]
look-up of "断断乎" finds only entry "断断乎たる" not "断断乎"
look-up of "サンバ" finds only "サン･バーン" not "サンバ", "サンバを踊る", "サンバ･ジ･エンヘード" etc.
Probably, it is a problem of the index and a lot work needs to be done, to fix this.

**Comment by stonerl** [comment]
Just one question is this seems to be a bug in WaDoku and not in GLB... @irisvogel

**Comment by ulrichapel** [comment]
Yes, this is a WaDoku bug.  Look-up in GLB is not perfect either, but for now and for writing new entries this is no problem.  

Am 07.01.2016 um 22:39 schrieb Toni F�rster:

**Comment by stonerl** [comment]
OK, I'm closing this one. You can open a new issue for GLB. I moved this one to the correct repo https://github.com/WaDoku/WaDokuClient/issues/2
