### ISSUE TITLE
Changing Password fails

### ISSUE THREAD

**Issue by stonerl** [WaDoku/GLB#15]
![screenshot-buddhismus-lexikon eu 2001 2015-12-17 12-35-48](https://cloud.githubusercontent.com/assets/2091312/11868813/e3da7ca6-a4ba-11e5-97b1-d5a02974f498.png)

**Comment by Netznarkose** [comment]
this is an assign-test

**Comment by stonerl** [comment]
Steps to reproduce:
1. Click on "Passwort vergessen?"
2. Enter your E-Mail-Address.
   3.Click on the link in the email you received.
   4.Try to change your password.

**Comment by Netznarkose** [comment]
can you make me an account on the original app in production www.buddhismus-lexikon.eu/ so I can enter the app and reenact these steps? my email: mmaintz@posteo.de you can send me the password by mail this is safer....

**Comment by stonerl** [comment]
@Netznarkose I added you as an admin to the staging db: buddhismus-lexikon.eu:2001 You should receive an E-Mail. But I send you the password by mail anyway.

**Comment by irisvogel** [comment]
Hi Max, I can not test it, since I don't think I have an account on the staging server. But I looked at the changes editing the profile.
Is it a feature, that you can not change the mail-address without resetting the password? In any case the password should be masked in the input fields.
Best
Iris

**Comment by stonerl** [comment]
@irisvogel AFAIK you should have an account on the staging site. Use the same mail and password as on the normal.

**Comment by Netznarkose** [comment]
@irisvogel 1) you are talking about changes I made in my pull request Issue #31 right?
Because this Issue here covers a bug that is much longer around and has something to do with the Gem Devise Configuration in production, which makes it hard to debug (at least for me) without access to the server. 
@irisvogel 2) Can you repost your justified questions concerning Issue #31 there in a comment so we can collect stuff related to that Issue there?

**Comment by Netznarkose** [comment]
@stonerl with pull request #33 merged I can click on the link 'passwort ändern' in the reset password email and get logged in and redirected to homepage directly, is this the appropriate behaviour, the way the app worked before the bug occured?

**Comment by stonerl** [comment]
I still get the error-message I'll send you the server-log by mail.

**Comment by stonerl** [comment]
@Netznarkose Yes the behavior you described is the way it worked before.

**Comment by irisvogel** [comment]
for development you can set the smtp server settings to your own mail server
http://stackoverflow.com/questions/11706277/action-mailer-smtp-google-apps

**Comment by stonerl** [comment]
@irisvogel your PR fixed it closing this issue now
