### ISSUE TITLE
refactoring and updating users_controller_spec.rb

### ISSUE THREAD

**Issue by Netznarkose** [WaDoku/GLB#27]
- [x] update the test syntax to rspec 3.4.1 
- [x] add tests that cover the current issues/changes (email-update, passwort-änderung etc.)
- [x] restructuring the global test syntax according to the controller actions
- [x] endow each test with a context of admin and editor
- [x] improve the readibility of the test descriptions
- [ ] write tests for the JSON format (branch: testing_json_included)

**Comment by stonerl** [comment]
I converted the list into a checklist.

**Comment by Netznarkose** [comment]
great....
