### ISSUE TITLE
Main fields disappeared in editing layout 

### ISSUE THREAD

**Issue by ulrichapel** [WaDoku/GLB#58]
the fields Übersetzung/Haupttext, Quellen SBDJ, Literatur SBDJ, Eigene Ergänzungen, Quellen Ergänzungen, Literatur Ergänzungen aren't displayed on http://buddhismus-lexikon.eu:2001/entries/66/edit.  With copy of the whole page the field content is in the clipboard.

**Comment by ulrichapel** [comment]
Formatting buttons aren't displayed either. Probably connected.

**Comment by Netznarkose** [comment]
solved now?
