### ISSUE TITLE
Button Labeling doesn't show in Firefox

### ISSUE THREAD

**Issue by ulrichapel** [WaDoku/GLB#62]
Working Layout http://buddhismus-lexikon.eu:2001/entries/149/edit the Buttons for Fachtermini, Werktitel original, Werktitel fremdspr., Sonstiges etc. aren't displayed on Firefox.  Safari works fine.

**Comment by Netznarkose** [comment]
this did not work in the previous version neither, right?

**Comment by Netznarkose** [comment]
fixed
<img width="1392" alt="screen shot 2018-04-18 at 4 20 01 pm" src="https://user-images.githubusercontent.com/10247813/38937868-88ecda4a-4324-11e8-940d-d7bc8ff10f93.png">
