### ISSUE TITLE
Wie Soll die GLB Landing-Page für Gäste gestaltet sein?

### ISSUE THREAD

**Issue by Netznarkose** [WaDoku/GLB#77]
derzeit werden Eintrags-Titel aber keine Übersetzungen angezeigt.

**Comment by Netznarkose** [comment]
Erklärungs-Nachricht für Gäste

**Comment by Netznarkose** [comment]
von @ulrichapel bereitgestellter Text:

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Projektbeschreibung 

Das Große Lexikon des Buddhismus möchte interessierte deutschsprachige Nutzende in umfassender und prägnanter Weise über die wichtigsten aber auch sehr spezifische Aspekte des Buddhismus informieren. Das Projekt startete als Übersetzung des japanischen Nachschlagewerks Sōgō Bukkyō Daijiten 総合仏教大辞典 (Sōgō Bukkyō Daijiten Henshū Iinkai (Hg.), Kyōto: Hōzōkan, 1987). Es enthält mittlerweile aber auch umfassende Bearbeitungen und sowie vollständig neu erstellte Einträge.

In geplanten ca. 10.000 Stichwörtern werden der frühen Buddhismus, seine Ausbreitung in Asien und darüber hinaus, die verschiedenen Schulen, Leben und Werke wichtiger buddhistischer Gelehrter, nüchterne Theorien – aber auch glühende Glaubensbekenntnisse –, buddhistische Kunst, Architektur sowie Musik, unterschiedliche Textformen und klassische Schriftensammlungen besonders aus China, Tibet, Thaliand, Korea und Japan behandelt. Dabei befindet sich bereits etwa ein Fünftel der Einträge in unterschiedlichen Zuständen der Bearbeitung.


Gedruckte Fassung

Die gedruckte Fassung des Lexikons erscheint bei iudicium, München <http://www.iudicium.de/>:  Erste Lieferung: A–Bai <http://www.iudicium.de/katalog/200-7.htm>, Zweite Lieferung: Bait–D <http://www.iudicium.de/katalog/86205-154.htm>, Zeittafeln und Karten
Indien · China · Japan · Westliche Rezeption <http://www.iudicium.de/katalog/528-1.htm>, Zeittafeln und Karten. Tibet · Südostasien · Korea <http://www.iudicium.de/katalog/86205-153.htm>.

Das Lexikon ist eine Veröffentlichung des EKŌ-Hauses der Japanischen Kultur e.V. <http://www.eko-haus.de>.


Zugang zum Online-Lexikon

Nicht eingeloggte Nutzende sehen zurzeit leider nur eine Liste der geplanten Einträge. Es ist vorgesehen, Einträge zur allgemeinen Nutzung freizugeben, bzw. Interessierten Zugang zu gewähren. Anfragen können gestellt werden an Ulrich Apel <apel@buddhismus-lexikon.eu> bzw. <apel@wadoku.de>.

**Comment by ulrichapel** [comment]
Nicht "Gedruckt Fassung" sondern "Gedruckte Fassung"
Die Mail-Adresse " apel@buddhismus-lexikon.eu" gibt es noch nicht, also erst einmal nur  apel@wadoku.de.
